# Generated by Django 3.1.7 on 2021-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
