# Generated by Django 3.1.7 on 2021-04-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='item',
            name='in_group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='item',
            name='requested',
        ),
        migrations.RemoveField(
            model_name='item',
            name='to_get_from',
        ),
        migrations.AlterUniqueTogether(
            name='merchant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='for_group',
        ),
        migrations.RemoveField(
            model_name='referenceitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='referenceitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='referenceitem',
            name='in_group',
        ),
        migrations.RemoveField(
            model_name='shopgroup',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='shopgroup',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='shopgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='support',
            name='log_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='ReferenceItem',
        ),
        migrations.DeleteModel(
            name='ShopGroup',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
